version: 2
updates:
  # Maintain dependencies for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"

  - package-ecosystem: npm
    directory: "/"
    schedule:
      interval: weekly
    open-pull-requests-limit: 15
    rebase-strategy: auto
    versioning-strategy: auto
    commit-message:
      prefix: chore
      include: scope
    labels:
      - "dependencies"
