# If you have questions about this integration please contact DevSecOps through
# #rex-sca-integration
name: SCA

on:
  push:
    branches: ["master", "main"]
  pull_request:
    branches: ["master", "main"]

jobs:
  snyk-cli:
    uses: atko-security/devsecops-tooling/.github/workflows/sca-scan.yml@main
    with:
      additional-arguments: "--exclude=scaffold"
      node-version: 24
    secrets: inherit
